# This is not intended for execution.
# Loads the per-install random event-bus authkey generated by install.sh,
# instead of a secret hardcoded in source (readable by anyone with repo
# access or a `ps`/proc dump of a running process).
import os
import stat
import pickle
import hmac

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# bin/iris-lite unwraps the passphrase-protected key (see tools/keywrap.py)
# into a tmpfs-only runtime directory and points this env var at it; the
# /etc/iris-lite fallback only matters for a raw-key-on-disk style deploy.
KEY_PATH = os.environ.get("IRIS_LITE_EVENTBUS_KEY_PATH", "/etc/iris-lite/eventbus.key")
_NONCE_LEN = 12
_FORMAT_VERSION = b"\x01"

def _reject_if_group_or_world_accessible(path: str, fd: int) -> None:
    # Defense in depth: install.sh chmods secrets 600, but this catches the
    # key silently regressing to a wider mode (e.g. a careless `chmod -R`,
    # or a restore from a backup that didn't preserve permissions).
    mode = stat.S_IMODE(os.fstat(fd).st_mode)
    if mode & (stat.S_IRWXG | stat.S_IRWXO):
        raise RuntimeError(
            f"{path} is group/world accessible (mode {oct(mode)}). "
            f"Refusing to use it - run: chmod 600 {path}"
        )

def load_authkey() -> bytes:
    try:
        with open(KEY_PATH, "rb") as f:
            _reject_if_group_or_world_accessible(KEY_PATH, f.fileno())
            key = f.read()
    except FileNotFoundError:
        raise RuntimeError(
            f"Event-bus authkey missing at {KEY_PATH}. Run install.sh, then "
            f"start via bin/iris-lite (it unwraps the passphrase-protected key)."
        )

    if len(key) < 16:
        raise RuntimeError(f"Event-bus authkey at {KEY_PATH} looks invalid.")

    return key

def _derive_payload_key(authkey: bytes) -> bytes:
    # multiprocessing.connection's authkey only drives an HMAC handshake at
    # connect time - the CaptureClass payloads sent afterward go over the
    # socket as plain pickle bytes. Derive a separate AES-256 key from the
    # same eventbus secret via HKDF (rather than reusing the raw authkey, or
    # a hand-rolled hash construction, as the AES key) so the handshake key
    # and the payload-encryption key are cryptographically independent.
    return HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=b"iris-lite-eventbus-salt-v1",
        info=b"iris-lite-eventbus-payload-v1",
    ).derive(authkey)

def encrypt_capture(obj, authkey: bytes) -> bytes:
    key = _derive_payload_key(authkey)
    nonce = os.urandom(_NONCE_LEN)
    plaintext = pickle.dumps(obj)
    ciphertext = AESGCM(key).encrypt(nonce, plaintext, _FORMAT_VERSION)
    return _FORMAT_VERSION + nonce + ciphertext

def decrypt_capture(blob: bytes, authkey: bytes):
    version, rest = blob[:1], blob[1:]
    if not hmac.compare_digest(version, _FORMAT_VERSION):
        raise ValueError(f"unsupported eventbus payload version {version!r}")

    key = _derive_payload_key(authkey)
    nonce, ciphertext = rest[:_NONCE_LEN], rest[_NONCE_LEN:]
    plaintext = AESGCM(key).decrypt(nonce, ciphertext, version)
    return pickle.loads(plaintext)

if __name__ == "__main__":
    raise RuntimeError("This isn't meant to be executed")
