# This is not intended for execution.
# Loads the per-install random event-bus authkey generated by install.sh,
# instead of a secret hardcoded in source (readable by anyone with repo
# access or a `ps`/proc dump of a running process).
KEY_PATH = "/etc/iris-lite/eventbus.key"

def load_authkey() -> bytes:
    try:
        with open(KEY_PATH, "rb") as f:
            key = f.read()
    except FileNotFoundError:
        raise RuntimeError(
            f"Event-bus authkey missing at {KEY_PATH}. Run install.sh first."
        )

    if len(key) < 16:
        raise RuntimeError(f"Event-bus authkey at {KEY_PATH} looks invalid.")

    return key

if __name__ == "__main__":
    raise RuntimeError("This isn't meant to be executed")
